#! /bin/sh

setxkbmap dvorak
sxhkd &

bspc monitor -d main music 3 4 5 6 7

bspc config border_width         0
bspc config window_gap           37

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop ^1 -l floating

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Google-chrome desktop=^1
bspc rule -a "Google Play Music Desktop Player" desktop=^2 follow=on
#bspc rule -a TelegramDesktop desktop=^3
#bspc rule -a Subl desktop=^4
#bspc rule -a Spotify desktop=^5
#bspc rule -a Lmms desktop=^5
#bspc rule -a mplayer2 state=floating
#bspc rule -a Gedit state=floating
#bspc rule -a Eog state=floating
#bspc rule -a Nautilus state=floating
#bspc rule -a File-roller state=floating
#bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config paddingless_monocle true
#bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr

#feh --bg-fill "/home/gamehelp16/Pictures/unsplashwall.jpg"
#feh --bg-fill ~/Pictures/zF1V6EE.jpg
feh --randomize --bg-fill ~/Pictures/wallpapers/
#gnome-wallpaper-changer &
compton -b &
xrdb -merge ~/.Xdefaults
redshift &
#/home/gamehelp16/allfloat.sh &

#panel &
polybar top &

#IM client
wmail &

#Notification server
dunst &

#Load .Xresources
xrdb -merge .Xresources &

xss-lock -- i3lock-fancy &
